'use strict';
const root=document.body.dataset.root||'',slug=document.body.dataset.lesson;
const el=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;};
const host=document.getElementById('quiz-content');let bank,attempt,answers={},position=0,started=false;
const memory={};
function readLayout(){try{return JSON.parse(localStorage.getItem('mitologia-order-v1-'+slug));}catch{return memory[slug]||null;}}
function saveLayout(layout){memory[slug]=layout;try{localStorage.setItem('mitologia-order-v1-'+slug,JSON.stringify(layout));}catch{/* Session memory remains usable if storage is disabled. */}}
async function start(){const b=document.getElementById('start-test');if(b)b.disabled=true;try{if(!bank){const res=await fetch(root+'data/tests/'+slug+'.json');if(!res.ok)throw Error('download');bank=await res.json();}const prepared=QuizCore.prepare(bank.questions,readLayout());attempt=prepared.questions;saveLayout(prepared.layout);answers={};position=0;started=true;renderQuestion();}catch(e){host.replaceChildren(el('p','Il test non è ancora disponibile offline. Riconnettiti per scaricare il modulo.'));const b=el('button','Riprova');b.id='start-test';b.onclick=start;host.append(b);}}
function focusQuiz(){const target=host.querySelector('legend,h3');if(target){target.tabIndex=-1;target.focus({preventScroll:true});}document.getElementById('test').scrollIntoView({block:'start'});}
function renderQuestion(){const q=attempt[position];host.replaceChildren();const status=el('div',undefined,'quiz-progress');status.append(el('span',`Domanda ${position+1} di ${attempt.length}`));const progress=el('progress');progress.max=attempt.length;progress.value=position;progress.setAttribute('aria-label','Domande completate');status.append(progress);host.append(status);
 const form=el('form');const fs=el('fieldset');fs.dataset.question=q.id;fs.append(el('legend',q.question));
 q.options.forEach((o,i)=>{const label=el('label',undefined,'answer');const input=el('input');input.type='radio';input.name='answer';input.value=o.id;input.checked=answers[q.id]===o.id;input.required=true;const letter=el('span',String.fromCharCode(65+i), 'letter');letter.setAttribute('aria-hidden','true');label.append(input,letter,el('span',o.text));fs.append(label);input.addEventListener('change',()=>{answers[q.id]=o.id;next.disabled=false;});});
 const actions=el('div',undefined,'quiz-actions');const back=el('button','← Indietro','secondary');back.type='button';back.disabled=position===0;back.onclick=()=>{position--;renderQuestion();};const next=el('button',position===attempt.length-1?'Concludi il test':'Successiva →');next.type='submit';next.disabled=!answers[q.id];actions.append(back,next);form.append(fs,actions);form.onsubmit=e=>{e.preventDefault();if(!answers[q.id])return;if(position<attempt.length-1){position++;renderQuestion();}else report();};host.append(form);focusQuiz();}
function report(){started=false;const s=QuizCore.score(attempt,answers);host.replaceChildren(el('h3','Il tuo risultato'));const grid=el('div',undefined,'score-grid');[[s.correct+'/'+s.total,'risposte corrette'],[s.wrong,'risposte errate'],[s.percent.toLocaleString('it-IT',{maximumFractionDigits:1})+'%','percentuale'],[s.grade.toLocaleString('it-IT',{minimumFractionDigits:1,maximumFractionDigits:1})+'/10','voto']].forEach(([v,t])=>{const b=el('div');b.append(el('strong',String(v)),el('span',t));grid.append(b);});host.append(grid,el('p',s.wrong?'Rileggi il recupero di ogni errore e torna al punto della lezione.':'Tutte le risposte sono corrette. Puoi rileggere la lezione o ripetere il test.'));
 s.errors.forEach(q=>{const item=el('article',undefined,'recovery');item.append(el('h3',q.question));const chosen=q.options.find(o=>o.id===answers[q.id]);const correct=q.options.find(o=>o.id===q.correctId);item.append(el('p','La tua risposta: '+(chosen?.text||'Nessuna risposta')),el('p','Risposta corretta: '+correct.text));const remedy=el('div',undefined,'remedy');remedy.append(el('strong','Mini-lezione di recupero'),el('p',q.recovery));item.append(remedy);const link=el('a','Rileggi la parte della lezione ↑');link.href=q.reference;item.append(link);host.append(item);});const retry=el('button','Riprova il test');retry.id='start-test';retry.style.marginTop='28px';retry.onclick=start;host.append(retry);focusQuiz();}
document.getElementById('start-test')?.addEventListener('click',start);
document.getElementById('text-size')?.addEventListener('click',e=>{const large=document.body.classList.toggle('large-text');e.currentTarget.setAttribute('aria-pressed',String(large));e.currentTarget.textContent=large?'Testo normale':'Testo più grande';});
// Returning from the back/forward cache is another fresh loading of an active test.
window.addEventListener('pageshow',e=>{if(e.persisted&&started)start();});
let installPrompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;document.getElementById('install').hidden=false;});document.getElementById('install').onclick=async()=>{if(installPrompt){await installPrompt.prompt();installPrompt=null;document.getElementById('install').hidden=true;}};
const offlineStatus=document.getElementById('offline-status');
async function registerOffline(){try{if(!('serviceWorker' in navigator))throw Error('unsupported');const reg=await navigator.serviceWorker.register(root+'sw.js');const ready=await navigator.serviceWorker.ready;function ask(){(navigator.serviceWorker.controller||ready.active)?.postMessage({type:'CACHE_STATUS'});}navigator.serviceWorker.addEventListener('message',e=>{if(e.data?.type==='CACHE_STATUS'){offlineStatus.textContent=e.data.ready?'Modulo pronto offline':'Download offline incompleto: riconnettiti e riprova.';document.getElementById('cache-retry').hidden=e.data.ready;}});navigator.serviceWorker.addEventListener('controllerchange',ask);ask();document.getElementById('cache-retry').onclick=()=>{offlineStatus.textContent='Download del modulo…';(navigator.serviceWorker.controller||reg.active)?.postMessage({type:'CACHE_RETRY'});};}catch{offlineStatus.textContent='Lettura online disponibile; download offline non riuscito.';}}
registerOffline();
