#!/usr/bin/env python3
"""Regenerate the versioned offline manifest after all site changes."""
from pathlib import Path
import hashlib,json
root=Path(__file__).resolve().parents[1]
files=sorted(p for p in root.rglob('*') if p.is_file() and (p.suffix in ['.html','.css','.js','.svg','.png','.jpg','.webp','.webmanifest','.json','.md']) and p.parts[len(root.parts)] not in ['tools','contenuti'] and p.name!='sw.js' and p.name!='package.json')
version=hashlib.sha256(b''.join(p.relative_to(root).as_posix().encode()+p.read_bytes() for p in files)).hexdigest()[:12]
urls=['./']+['./'+p.relative_to(root).as_posix() for p in files]
source="""/* Generated by tools/cache.py. Only this PWA's scope and cache are managed. */
'use strict';
const VERSION = __VERSION__;
const SCOPE = self.registration.scope;
const CACHE_PREFIX = 'gbprof-antologia-' + encodeURIComponent(new URL(SCOPE).pathname) + '-';
const CACHE = CACHE_PREFIX + VERSION;
const FILES = __FILES__;
self.addEventListener('install', event => {
 event.waitUntil(caches.open(CACHE).then(cache => cache.addAll(FILES.map(path => new URL(path, SCOPE).href))));
});
self.addEventListener('activate', event => {
 event.waitUntil(caches.keys().then(keys => Promise.all(keys.filter(key => key.startsWith(CACHE_PREFIX) && key !== CACHE).map(key => caches.delete(key)))).then(() => self.clients.claim()));
});
self.addEventListener('message', event => {
 if(event.data && event.data.type === 'SKIP_WAITING') self.skipWaiting();
});
self.addEventListener('fetch', event => {
 const request = event.request, url = new URL(request.url);
 if(request.method !== 'GET' || url.origin !== self.location.origin || !url.href.startsWith(SCOPE)) return;
 event.respondWith((async () => {
  const cache = await caches.open(CACHE);
  // Query strings carry return/resume state, not different lesson content.
  const known = await cache.match(request, {ignoreSearch:true});
  if(known) return known;
  try {return await fetch(request)} catch {
   if(request.mode === 'navigate') return await cache.match(new URL('offline.html', SCOPE).href);
   return Response.error();
  }
 })());
});
""".replace('__VERSION__',json.dumps(version)).replace('__FILES__',json.dumps(urls,ensure_ascii=False,indent=1))
(root/'sw.js').write_text(source)
print(json.dumps({'version':version,'cached_files':len(urls),'bytes':sum(p.stat().st_size for p in files)}))
