/* Generated by tools/cache.py. Only this PWA's scope and cache are managed. */
'use strict';
const VERSION = "6aa5745327ae";
const SCOPE = self.registration.scope;
const CACHE_PREFIX = 'gbprof-antologia-' + encodeURIComponent(new URL(SCOPE).pathname) + '-';
const CACHE = CACHE_PREFIX + VERSION;
const FILES = [
 "./",
 "./README.md",
 "./assets/app.js",
 "./assets/catalog.js",
 "./assets/icons/icon-192.png",
 "./assets/icons/icon-512.png",
 "./assets/icons/maskable-512.png",
 "./assets/images/01-racconto.webp",
 "./assets/images/02-mito.webp",
 "./assets/images/03-limite.webp",
 "./assets/images/04-edipo.webp",
 "./assets/images/05-antigone.webp",
 "./assets/images/06-paride.webp",
 "./assets/images/07-achille.webp",
 "./assets/images/08-iliade.webp",
 "./assets/images/09-odissea.webp",
 "./assets/images/10-raccontare.webp",
 "./assets/images/c1-comunicare.webp",
 "./assets/images/c2-giudicare.webp",
 "./assets/images/c3-dissentire.webp",
 "./assets/images/c4-conflitto.webp",
 "./assets/images/c5-identita.webp",
 "./assets/mappe/00-percorso.png",
 "./assets/mappe/00-percorso.svg",
 "./assets/mappe/01-racconto.png",
 "./assets/mappe/01-racconto.svg",
 "./assets/mappe/02-mito.png",
 "./assets/mappe/02-mito.svg",
 "./assets/mappe/03-limite.png",
 "./assets/mappe/03-limite.svg",
 "./assets/mappe/04-edipo.png",
 "./assets/mappe/04-edipo.svg",
 "./assets/mappe/05-antigone.png",
 "./assets/mappe/05-antigone.svg",
 "./assets/mappe/06-paride.png",
 "./assets/mappe/06-paride.svg",
 "./assets/mappe/07-achille.png",
 "./assets/mappe/07-achille.svg",
 "./assets/mappe/08-iliade.png",
 "./assets/mappe/08-iliade.svg",
 "./assets/mappe/09-odissea.png",
 "./assets/mappe/09-odissea.svg",
 "./assets/mappe/10-raccontare.png",
 "./assets/mappe/10-raccontare.svg",
 "./assets/mappe/c1-comunicare.png",
 "./assets/mappe/c1-comunicare.svg",
 "./assets/mappe/c2-giudicare.png",
 "./assets/mappe/c2-giudicare.svg",
 "./assets/mappe/c3-dissentire.png",
 "./assets/mappe/c3-dissentire.svg",
 "./assets/mappe/c4-conflitto.png",
 "./assets/mappe/c4-conflitto.svg",
 "./assets/mappe/c5-identita.png",
 "./assets/mappe/c5-identita.svg",
 "./assets/style.css",
 "./cittadinanza.html",
 "./docente.html",
 "./docs/analisi-fonti.md",
 "./docs/anteprima-home.jpg",
 "./docs/anteprima-mappa.jpg",
 "./docs/anteprima-tablet-orizzontale.jpg",
 "./docs/anteprima-tablet-verticale.jpg",
 "./docs/avanzamento.md",
 "./docs/collaudo-browser.md",
 "./docs/collaudo.md",
 "./docs/contrast-checks.json",
 "./docs/docente-body.html",
 "./docs/immagini.json",
 "./docs/inventario-fonti.md",
 "./docs/map-checks.json",
 "./docs/matrice-funzioni.md",
 "./docs/nota-docente.md",
 "./docs/prompts-illustrazioni.json",
 "./docs/static-checks.json",
 "./docs/worker-checks.json",
 "./guida.html",
 "./index.html",
 "./lezioni/01-racconto.html",
 "./lezioni/02-mito.html",
 "./lezioni/03-limite.html",
 "./lezioni/04-edipo.html",
 "./lezioni/05-antigone.html",
 "./lezioni/06-paride.html",
 "./lezioni/07-achille.html",
 "./lezioni/08-iliade.html",
 "./lezioni/09-odissea.html",
 "./lezioni/10-raccontare.html",
 "./lezioni/c1-comunicare.html",
 "./lezioni/c2-giudicare.html",
 "./lezioni/c3-dissentire.html",
 "./lezioni/c4-conflitto.html",
 "./lezioni/c5-identita.html",
 "./manifest.webmanifest",
 "./mappe.html",
 "./offline.html"
];
self.addEventListener('install', event => {
 event.waitUntil(caches.open(CACHE).then(cache => cache.addAll(FILES.map(path => new URL(path, SCOPE).href))));
});
self.addEventListener('activate', event => {
 event.waitUntil(caches.keys().then(keys => Promise.all(keys.filter(key => key.startsWith(CACHE_PREFIX) && key !== CACHE).map(key => caches.delete(key)))).then(() => self.clients.claim()));
});
self.addEventListener('message', event => {
 if(event.data && event.data.type === 'SKIP_WAITING') self.skipWaiting();
});
self.addEventListener('fetch', event => {
 const request = event.request, url = new URL(request.url);
 if(request.method !== 'GET' || url.origin !== self.location.origin || !url.href.startsWith(SCOPE)) return;
 event.respondWith((async () => {
  const cache = await caches.open(CACHE);
  // Query strings carry return/resume state, not different lesson content.
  const known = await cache.match(request, {ignoreSearch:true});
  if(known) return known;
  try {return await fetch(request)} catch {
   if(request.mode === 'navigate') return await cache.match(new URL('offline.html', SCOPE).href);
   return Response.error();
  }
 })());
});
