from pathlib import Path
import hashlib,json
R=Path(__file__).resolve().parents[1]
files=sorted(p.relative_to(R).as_posix() for p in R.rglob('*') if p.is_file() and p.suffix in ['.html','.css','.js','.webp','.png','.json','.webmanifest'] and p.name!='sw.js' and p.relative_to(R).parts[0] not in ['tools','tests'] and 'sources' not in p.relative_to(R).parts and p.name!='paragraphs.json')
digest=hashlib.sha256(b''.join((R/f).read_bytes() for f in files)).hexdigest()[:12]
s='''/* Generated by tools/build-sw.py. Scope is restricted to this module. */
const CACHE='mitologia-'''+digest+"'"+''';
const ASSETS='''+json.dumps(files)+''';
const assetURLs=ASSETS.map(path=>new URL(path,self.registration.scope).href);
async function fill(){const cache=await caches.open(CACHE);await Promise.all(assetURLs.map(async url=>{if(await cache.match(url))return;const response=await fetch(url,{cache:'reload'});if(!response.ok)throw Error('Asset '+url);await cache.put(url,response);}));}
async function complete(){const cache=await caches.open(CACHE);const all=await Promise.all(assetURLs.map(url=>cache.match(url)));return all.every(Boolean);}
self.addEventListener('install',event=>event.waitUntil(fill().then(()=>self.skipWaiting())));
self.addEventListener('activate',event=>event.waitUntil((async()=>{const keys=await caches.keys();await Promise.all(keys.filter(k=>k.startsWith('mitologia-')&&k!==CACHE).map(k=>caches.delete(k)));await self.clients.claim();})()));
self.addEventListener('message',event=>event.waitUntil((async()=>{if(!['CACHE_STATUS','CACHE_RETRY'].includes(event.data?.type))return;if(event.data.type==='CACHE_RETRY'){try{await fill();}catch{}}const ready=await complete();event.source?.postMessage({type:'CACHE_STATUS',ready});})()));
self.addEventListener('fetch',event=>{if(event.request.method!=='GET')return;const url=new URL(event.request.url);if(!url.href.startsWith(self.registration.scope))return;event.respondWith((async()=>{const cache=await caches.open(CACHE);let normalized=new URL(url);normalized.search='';if(normalized.pathname.endsWith('/'))normalized.pathname+='index.html';const cached=await cache.match(normalized.href);if(cached)return cached;try{return await fetch(event.request);}catch{if(event.request.mode==='navigate')return await cache.match(new URL('offline.html',self.registration.scope).href);return Response.error();}})());});
'''
(R/'sw.js').write_text(s)
print(CACHE if False else 'Cache version '+digest+', assets '+str(len(files)))
