const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const {JSDOM,VirtualConsole}=require('jsdom');
const root=path.resolve(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8');
const raw=read('assets/data.js');const dc={window:{}};vm.runInNewContext(raw,dc);const data=dc.window.MITI_DATA;
function page(file,storage,blocked=false){const errors=[];const vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));const dom=new JSDOM(read(file),{url:'https://example.test/I-anno/Lezioni/Miti/'+file,runScripts:'outside-only',virtualConsole:vc});const w=dom.window;w.confirm=()=>true;w.URL.createObjectURL=()=> 'blob:download';w.URL.revokeObjectURL=()=>{};w.HTMLAnchorElement.prototype.click=function(){};if(storage)w.localStorage.setItem('gbprof-miti-v1',storage);if(blocked)Object.defineProperty(w,'localStorage',{get(){throw Error('Denied');}});w.eval(raw);w.eval(read('assets/app.js'));return {dom,w,d:w.document,errors};}
const click=(d,s)=>{const el=d.querySelector(s);assert.ok(el,s);el.click();};
const submit=(w,d)=>d.querySelector('form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));
for(const lesson of data){test('Lezione '+lesson.id+': errore → recupero → persistenza',()=>{const {dom,w,d,errors}=page('lezioni/'+lesson.slug+'.html');click(d,'[data-panel="test"]');assert.equal(d.querySelector('#test').hidden,false);assert.equal(d.querySelectorAll('fieldset').length,5);submit(w,d);assert.match(d.querySelector('[role="alert"]').textContent,/Manca/);assert.equal(JSON.parse(w.localStorage.getItem('gbprof-miti-v1')).tests['lesson-'+lesson.id]?.length||0,0);
lesson.questions.forEach((q,i)=>click(d,`input[name="q${i}"][value="${i===1?(q[2]+1)%3:q[2]}"]`));submit(w,d);assert.match(d.querySelector('.score').textContent,/4 risposte corrette su 5/);assert.equal(d.querySelectorAll('.wrong').length,1);const btn=[...d.querySelectorAll('#quiz button')].find(b=>b.textContent.includes('solo gli errori'));btn.click();assert.equal(d.querySelectorAll('fieldset').length,1);click(d,`input[name="q1"][value="${lesson.questions[1][2]}"]`);submit(w,d);assert.match(d.querySelector('.score').textContent,/5 risposte corrette su 5/);const saved=w.localStorage.getItem('gbprof-miti-v1');const st=JSON.parse(saved);assert.equal(st.tests['lesson-'+lesson.id].length,2);assert.equal(st.tests['lesson-'+lesson.id][0].answers[1],(lesson.questions[1][2]+1)%3);assert.equal(st.tests['lesson-'+lesson.id][1].answers[1],lesson.questions[1][2]);assert.equal(errors.length,0);dom.window.close();const reload=page('lezioni/'+lesson.slug+'.html',saved);assert.match(reload.d.querySelector('.score').textContent,/5 risposte corrette su 5/);reload.dom.window.close();});}
test('Taccuino, completamento, preferenze ed esportazione',()=>{const {dom,w,d}=page('lezioni/edipo-re.html');click(d,'[data-side="notes"]');const note=d.querySelector('#notes');note.value='Un nesso fra identità e ricerca.';note.dispatchEvent(new w.Event('input'));const prod=d.querySelector('#production');prod.value='Storyboard di sei vignette.';prod.dispatchEvent(new w.Event('input'));click(d,'[data-complete]');const slider=d.querySelector('#font-size');slider.value=26;slider.dispatchEvent(new w.Event('input'));assert.equal(d.documentElement.style.getPropertyValue('--reading-size'),'26px');const state=JSON.parse(w.localStorage.getItem('gbprof-miti-v1'));assert.equal(state.lessons[2].notes,note.value);assert.equal(state.lessons[2].production,prod.value);assert.equal(state.lessons[2].complete,true);assert.equal(state.prefs.size,26);let blobs=[];w.URL.createObjectURL=b=>{blobs.push(b);return 'blob:download';};click(d,'[data-export="txt"]');click(d,'[data-export="json"]');assert.equal(blobs.length,2);assert.equal(blobs[1].type,'application/json');dom.window.close();});
test('Selezione del testo conserva un passo senza eseguire HTML',()=>{const {dom,w,d}=page('lezioni/testo-al-centro.html');const p=d.querySelector('#lettura p:not(.eyebrow)');const range=d.createRange();range.selectNodeContents(p);w.getSelection().removeAllRanges();w.getSelection().addRange(range);d.dispatchEvent(new w.Event('selectionchange'));click(d,'[data-side="notes"]');click(d,'#capture');assert.equal(d.querySelectorAll('.quote').length,1);assert.equal(JSON.parse(w.localStorage.getItem('gbprof-miti-v1')).lessons[1].quotes.length,1);click(d,'.quote button');assert.equal(d.querySelectorAll('.quote').length,0);dom.window.close();});
test('Ripasso finale: dodici risposte corrette',()=>{const {dom,w,d}=page('ripasso.html');const qs=data.flatMap(x=>[x.questions[0],x.questions[4]]);assert.equal(d.querySelectorAll('fieldset').length,12);qs.forEach((q,i)=>click(d,`input[name="q${i}"][value="${q[2]}"]`));submit(w,d);assert.match(d.querySelector('.score').textContent,/12 risposte corrette su 12/);assert.match(d.querySelector('.score').textContent,/10\/10/);dom.window.close();});
test('Ricerca home, ripresa e nessun errore con storage indisponibile',()=>{const {dom,w,d}=page('index.html');const search=d.querySelector('#search');search.value='Polibo';search.dispatchEvent(new w.Event('input'));assert.ok([...d.querySelectorAll('[data-card]')].some(c=>!c.hidden));search.value='zzzzzz';search.dispatchEvent(new w.Event('input'));assert.equal([...d.querySelectorAll('[data-card]')].filter(c=>!c.hidden).length,0);dom.window.close();const no=page('lezioni/iliade.html',null,true);assert.equal(no.d.querySelectorAll('fieldset').length,5);assert.equal(no.errors.length,0);no.dom.window.close();});
test('Backup validation ignores foreign keys and rejects invalid payloads',()=>{const c=require('../assets/app.js');assert.throws(()=>c.validateState({version:7}));const s=c.blank();s.other='foreign';s.lessons[3]={notes:'<script>alert(1)</script>',complete:true,quotes:['safe']};s.tests.final=[{answers:Array(12).fill(5)}];const v=c.validateState(s);assert.equal(v.other,undefined);assert.equal(v.lessons[3].notes,'<script>alert(1)</script>');assert.equal(v.tests.final.length,0);});
test('Cache isolata, copertura risorse, nessun fallback di pagina per risorse assenti',async()=>{const events={},stores=new Map(),scope='https://example.test/I-anno/Lezioni/Miti/';let skipped=0,claimed=0;const c={URL,encodeURIComponent,Promise,self:{location:{href:scope+'service-worker.js'},registration:{scope},addEventListener:(k,v)=>events[k]=v,skipWaiting:async()=>skipped++,clients:{claim:async()=>claimed++}},caches:{open:async k=>{if(!stores.has(k))stores.set(k,new Map());const m=stores.get(k);return{addAll:async urls=>{urls.forEach(u=>m.set(u,{url:u}));},match:async u=>m.get(u)};},keys:async()=>[...stores.keys()],delete:async k=>stores.delete(k)},fetch:async req=>({network:req.url})};vm.runInNewContext(read('service-worker.js'),c);stores.set('unrelated-pwa',new Map());let pending;events.install({waitUntil:p=>pending=p});await pending;assert.equal(skipped,1);events.activate({waitUntil:p=>pending=p});await pending;assert.equal(claimed,1);assert.ok(stores.has('unrelated-pwa'));let response;events.fetch({request:{url:scope+'lezioni/antigone.html',method:'GET'},respondWith:p=>response=p});assert.equal((await response).url,scope+'lezioni/antigone.html');let intercepted=false;events.fetch({request:{url:'https://outside.test/video',method:'GET'},respondWith:()=>intercepted=true});assert.equal(intercepted,false);events.fetch({request:{url:scope+'missing.png',method:'GET'},respondWith:()=>intercepted=true});assert.equal(intercepted,false);let message;events.message({data:{type:'CHECK_READY'},source:{postMessage:m=>message=m},waitUntil:p=>pending=p});await pending;assert.equal(message.type,'OFFLINE_READY');});
test('Tutti i percorsi interni e gli ID di destinazione esistono',()=>{const files=fs.readdirSync(root).filter(p=>p.endsWith('.html')).concat(fs.readdirSync(path.join(root,'lezioni')).filter(p=>p.endsWith('.html')).map(p=>'lezioni/'+p));for(const f of files){const dom=new JSDOM(read(f));const doc=dom.window.document;assert.equal(doc.documentElement.lang,'it');assert.equal(doc.querySelectorAll('h1').length,1);assert.ok(doc.querySelector('main'));for(const el of doc.querySelectorAll('[href],[src]')){const url=el.getAttribute('href')||el.getAttribute('src');if(!url||/^(https?:|mailto:|data:)/.test(url))continue;const [part,hash]=url.split('#');const target=part?path.resolve(root,path.dirname(f),part):path.resolve(root,f);assert.ok(fs.existsSync(target),f+' → '+url);if(hash){const targetDom=part?new JSDOM(fs.readFileSync(target,'utf8')):dom;assert.ok(targetDom.window.document.getElementById(hash),f+' #'+hash);if(part)targetDom.window.close();}}for(const im of doc.querySelectorAll('img'))assert.ok(im.hasAttribute('alt'));dom.window.close();}});
